language: java
jdk: oraclejdk8
jobs:
  include:
    - stage: "Test Server"
      script: cd Trajectory-Server && mvn clean install exec:java
    - stage: "Test Client"
      script: cd Trajectory-Client && mvn clean install exec:java
